// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9F7tgueQcxptPz4_DHpTr_cEy5P1oG0A',
    appId: '1:652662656997:web:4ee9853e3e9ee8d8a6a90c',
    messagingSenderId: '652662656997',
    projectId: 'pickup-monitor-aaba3',
    authDomain: 'pickup-monitor-aaba3.firebaseapp.com',
    storageBucket: 'pickup-monitor-aaba3.firebasestorage.app',
    measurementId: 'G-4G9QSF3HRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC91NWpzJAWUjkZ5gVYHDc2Ad4t3lnKBU',
    appId: '1:652662656997:android:3573d47cb8ebf66da6a90c',
    messagingSenderId: '652662656997',
    projectId: 'pickup-monitor-aaba3',
    storageBucket: 'pickup-monitor-aaba3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Yky50nEoGRlhAM2jc0LDSbEkAzS83sM',
    appId: '1:652662656997:ios:70143dd46054c384a6a90c',
    messagingSenderId: '652662656997',
    projectId: 'pickup-monitor-aaba3',
    storageBucket: 'pickup-monitor-aaba3.firebasestorage.app',
    iosBundleId: 'com.example.pickupMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3Yky50nEoGRlhAM2jc0LDSbEkAzS83sM',
    appId: '1:652662656997:ios:70143dd46054c384a6a90c',
    messagingSenderId: '652662656997',
    projectId: 'pickup-monitor-aaba3',
    storageBucket: 'pickup-monitor-aaba3.firebasestorage.app',
    iosBundleId: 'com.example.pickupMonitor',
  );
}